#!/bin/bash
echo "============================================="
echo $SOURCE_BRANCH
echo $SOURCE_COMMIT
echo $COMMIT_MSG
echo $DOCKER_REPO
echo $DOCKERFILE_PATH
echo $DOCKER_TAG
echo $IMAGE_NAME
echo "============================================="

if [ "$DOCKER_TAG" == "master" ] ; then
    VERSION=master
else
    source hooks/getversion.sh
fi

echo "Using Zephyr-Version: ${VERSION}"

docker build --build-arg ZEPHYR_VERSION=$VERSION -f $DOCKERFILE_PATH -t $IMAGE_NAME .